/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTimelineRouteImport } from './routes/_authenticated/timeline'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPredictionsRouteImport } from './routes/_authenticated/predictions'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedKingdomRouteImport } from './routes/_authenticated/kingdom'
import { Route as AuthenticatedExamsRouteImport } from './routes/_authenticated/exams'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedTimelineYearRouteImport } from './routes/_authenticated/timeline.$year'
import { Route as AuthenticatedStudentWeeklyQuestionRouteImport } from './routes/_authenticated/student.weekly-question'
import { Route as AuthenticatedExamsExamIdRouteImport } from './routes/_authenticated/exams.$examId'
import { Route as AuthenticatedEventsEventIdRouteImport } from './routes/_authenticated/events.$eventId'
import { Route as AuthenticatedAdminWeeklyWinnersRouteImport } from './routes/_authenticated/admin.weekly-winners'
import { Route as AuthenticatedAdminStyleRouteImport } from './routes/_authenticated/admin.style'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin.students'
import { Route as AuthenticatedAdminExamsRouteImport } from './routes/_authenticated/admin.exams'
import { Route as AuthenticatedStudentVideosIndexRouteImport } from './routes/_authenticated/student.videos.index'
import { Route as AuthenticatedStudentLiveIndexRouteImport } from './routes/_authenticated/student.live.index'
import { Route as AuthenticatedStudentHistoryIndexRouteImport } from './routes/_authenticated/student.history.index'
import { Route as AuthenticatedAdminWeeklyQuestionIndexRouteImport } from './routes/_authenticated/admin.weekly-question.index'
import { Route as AuthenticatedAdminVideosIndexRouteImport } from './routes/_authenticated/admin.videos.index'
import { Route as AuthenticatedAdminSystemHealthIndexRouteImport } from './routes/_authenticated/admin.system-health.index'
import { Route as AuthenticatedAdminSettingsIndexRouteImport } from './routes/_authenticated/admin.settings.index'
import { Route as AuthenticatedAdminNotificationsIndexRouteImport } from './routes/_authenticated/admin.notifications.index'
import { Route as AuthenticatedAdminLiveIndexRouteImport } from './routes/_authenticated/admin.live.index'
import { Route as AuthenticatedAdminLeaderboardIndexRouteImport } from './routes/_authenticated/admin.leaderboard.index'
import { Route as AuthenticatedAdminKingdomIndexRouteImport } from './routes/_authenticated/admin.kingdom.index'
import { Route as AuthenticatedAdminHistoryIndexRouteImport } from './routes/_authenticated/admin.history.index'
import { Route as AuthenticatedAdminEventsIndexRouteImport } from './routes/_authenticated/admin.events.index'
import { Route as AuthenticatedAdminAnnouncementsIndexRouteImport } from './routes/_authenticated/admin.announcements.index'
import { Route as AuthenticatedStudentVideosVideoIdRouteImport } from './routes/_authenticated/student.videos.$videoId'
import { Route as AuthenticatedStudentLiveLiveIdRouteImport } from './routes/_authenticated/student.live.$liveId'
import { Route as AuthenticatedStudentHistoryEraIdRouteImport } from './routes/_authenticated/student.history.$eraId'
import { Route as AuthenticatedExamsExamIdResultRouteImport } from './routes/_authenticated/exams.$examId.result'
import { Route as AuthenticatedAdminVideosNewRouteImport } from './routes/_authenticated/admin.videos.new'
import { Route as AuthenticatedAdminVideosVideoIdRouteImport } from './routes/_authenticated/admin.videos.$videoId'
import { Route as AuthenticatedAdminResultsStudentIdRouteImport } from './routes/_authenticated/admin.results.$studentId'
import { Route as AuthenticatedAdminLiveNewRouteImport } from './routes/_authenticated/admin.live.new'
import { Route as AuthenticatedAdminLiveLiveIdRouteImport } from './routes/_authenticated/admin.live.$liveId'
import { Route as AuthenticatedAdminHistoryNewEraRouteImport } from './routes/_authenticated/admin.history.new-era'
import { Route as AuthenticatedAdminHistoryEraIdRouteImport } from './routes/_authenticated/admin.history.$eraId'
import { Route as AuthenticatedAdminExamsExamIdRouteImport } from './routes/_authenticated/admin.exams.$examId'
import { Route as AuthenticatedAdminHistoryEditEraIdRouteImport } from './routes/_authenticated/admin.history.edit.$eraId'
import { Route as AuthenticatedAdminHistoryEraIdNewEventRouteImport } from './routes/_authenticated/admin.history.$eraId.new-event'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTimelineRoute = AuthenticatedTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPredictionsRoute =
  AuthenticatedPredictionsRouteImport.update({
    id: '/predictions',
    path: '/predictions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKingdomRoute = AuthenticatedKingdomRouteImport.update({
  id: '/kingdom',
  path: '/kingdom',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamsRoute = AuthenticatedExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedTimelineYearRoute =
  AuthenticatedTimelineYearRouteImport.update({
    id: '/$year',
    path: '/$year',
    getParentRoute: () => AuthenticatedTimelineRoute,
  } as any)
const AuthenticatedStudentWeeklyQuestionRoute =
  AuthenticatedStudentWeeklyQuestionRouteImport.update({
    id: '/student/weekly-question',
    path: '/student/weekly-question',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamsExamIdRoute =
  AuthenticatedExamsExamIdRouteImport.update({
    id: '/$examId',
    path: '/$examId',
    getParentRoute: () => AuthenticatedExamsRoute,
  } as any)
const AuthenticatedEventsEventIdRoute =
  AuthenticatedEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminWeeklyWinnersRoute =
  AuthenticatedAdminWeeklyWinnersRouteImport.update({
    id: '/weekly-winners',
    path: '/weekly-winners',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStyleRoute = AuthenticatedAdminStyleRouteImport.update({
  id: '/style',
  path: '/style',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminExamsRoute = AuthenticatedAdminExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedStudentVideosIndexRoute =
  AuthenticatedStudentVideosIndexRouteImport.update({
    id: '/student/videos/',
    path: '/student/videos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentLiveIndexRoute =
  AuthenticatedStudentLiveIndexRouteImport.update({
    id: '/student/live/',
    path: '/student/live/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentHistoryIndexRoute =
  AuthenticatedStudentHistoryIndexRouteImport.update({
    id: '/student/history/',
    path: '/student/history/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminWeeklyQuestionIndexRoute =
  AuthenticatedAdminWeeklyQuestionIndexRouteImport.update({
    id: '/weekly-question/',
    path: '/weekly-question/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVideosIndexRoute =
  AuthenticatedAdminVideosIndexRouteImport.update({
    id: '/videos/',
    path: '/videos/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSystemHealthIndexRoute =
  AuthenticatedAdminSystemHealthIndexRouteImport.update({
    id: '/system-health/',
    path: '/system-health/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsIndexRoute =
  AuthenticatedAdminSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotificationsIndexRoute =
  AuthenticatedAdminNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLiveIndexRoute =
  AuthenticatedAdminLiveIndexRouteImport.update({
    id: '/live/',
    path: '/live/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLeaderboardIndexRoute =
  AuthenticatedAdminLeaderboardIndexRouteImport.update({
    id: '/leaderboard/',
    path: '/leaderboard/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminKingdomIndexRoute =
  AuthenticatedAdminKingdomIndexRouteImport.update({
    id: '/kingdom/',
    path: '/kingdom/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHistoryIndexRoute =
  AuthenticatedAdminHistoryIndexRouteImport.update({
    id: '/history/',
    path: '/history/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventsIndexRoute =
  AuthenticatedAdminEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnnouncementsIndexRoute =
  AuthenticatedAdminAnnouncementsIndexRouteImport.update({
    id: '/announcements/',
    path: '/announcements/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedStudentVideosVideoIdRoute =
  AuthenticatedStudentVideosVideoIdRouteImport.update({
    id: '/student/videos/$videoId',
    path: '/student/videos/$videoId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentLiveLiveIdRoute =
  AuthenticatedStudentLiveLiveIdRouteImport.update({
    id: '/student/live/$liveId',
    path: '/student/live/$liveId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentHistoryEraIdRoute =
  AuthenticatedStudentHistoryEraIdRouteImport.update({
    id: '/student/history/$eraId',
    path: '/student/history/$eraId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamsExamIdResultRoute =
  AuthenticatedExamsExamIdResultRouteImport.update({
    id: '/result',
    path: '/result',
    getParentRoute: () => AuthenticatedExamsExamIdRoute,
  } as any)
const AuthenticatedAdminVideosNewRoute =
  AuthenticatedAdminVideosNewRouteImport.update({
    id: '/videos/new',
    path: '/videos/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVideosVideoIdRoute =
  AuthenticatedAdminVideosVideoIdRouteImport.update({
    id: '/videos/$videoId',
    path: '/videos/$videoId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResultsStudentIdRoute =
  AuthenticatedAdminResultsStudentIdRouteImport.update({
    id: '/results/$studentId',
    path: '/results/$studentId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLiveNewRoute =
  AuthenticatedAdminLiveNewRouteImport.update({
    id: '/live/new',
    path: '/live/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLiveLiveIdRoute =
  AuthenticatedAdminLiveLiveIdRouteImport.update({
    id: '/live/$liveId',
    path: '/live/$liveId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHistoryNewEraRoute =
  AuthenticatedAdminHistoryNewEraRouteImport.update({
    id: '/history/new-era',
    path: '/history/new-era',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHistoryEraIdRoute =
  AuthenticatedAdminHistoryEraIdRouteImport.update({
    id: '/history/$eraId',
    path: '/history/$eraId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminExamsExamIdRoute =
  AuthenticatedAdminExamsExamIdRouteImport.update({
    id: '/$examId',
    path: '/$examId',
    getParentRoute: () => AuthenticatedAdminExamsRoute,
  } as any)
const AuthenticatedAdminHistoryEditEraIdRoute =
  AuthenticatedAdminHistoryEditEraIdRouteImport.update({
    id: '/history/edit/$eraId',
    path: '/history/edit/$eraId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHistoryEraIdNewEventRoute =
  AuthenticatedAdminHistoryEraIdNewEventRouteImport.update({
    id: '/new-event',
    path: '/new-event',
    getParentRoute: () => AuthenticatedAdminHistoryEraIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/assistant': typeof AuthenticatedAssistantRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exams': typeof AuthenticatedExamsRouteWithChildren
  '/kingdom': typeof AuthenticatedKingdomRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/predictions': typeof AuthenticatedPredictionsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/timeline': typeof AuthenticatedTimelineRouteWithChildren
  '/admin/exams': typeof AuthenticatedAdminExamsRouteWithChildren
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/style': typeof AuthenticatedAdminStyleRoute
  '/admin/weekly-winners': typeof AuthenticatedAdminWeeklyWinnersRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/exams/$examId': typeof AuthenticatedExamsExamIdRouteWithChildren
  '/student/weekly-question': typeof AuthenticatedStudentWeeklyQuestionRoute
  '/timeline/$year': typeof AuthenticatedTimelineYearRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/exams/$examId': typeof AuthenticatedAdminExamsExamIdRoute
  '/admin/history/$eraId': typeof AuthenticatedAdminHistoryEraIdRouteWithChildren
  '/admin/history/new-era': typeof AuthenticatedAdminHistoryNewEraRoute
  '/admin/live/$liveId': typeof AuthenticatedAdminLiveLiveIdRoute
  '/admin/live/new': typeof AuthenticatedAdminLiveNewRoute
  '/admin/results/$studentId': typeof AuthenticatedAdminResultsStudentIdRoute
  '/admin/videos/$videoId': typeof AuthenticatedAdminVideosVideoIdRoute
  '/admin/videos/new': typeof AuthenticatedAdminVideosNewRoute
  '/exams/$examId/result': typeof AuthenticatedExamsExamIdResultRoute
  '/student/history/$eraId': typeof AuthenticatedStudentHistoryEraIdRoute
  '/student/live/$liveId': typeof AuthenticatedStudentLiveLiveIdRoute
  '/student/videos/$videoId': typeof AuthenticatedStudentVideosVideoIdRoute
  '/admin/announcements/': typeof AuthenticatedAdminAnnouncementsIndexRoute
  '/admin/events/': typeof AuthenticatedAdminEventsIndexRoute
  '/admin/history/': typeof AuthenticatedAdminHistoryIndexRoute
  '/admin/kingdom/': typeof AuthenticatedAdminKingdomIndexRoute
  '/admin/leaderboard/': typeof AuthenticatedAdminLeaderboardIndexRoute
  '/admin/live/': typeof AuthenticatedAdminLiveIndexRoute
  '/admin/notifications/': typeof AuthenticatedAdminNotificationsIndexRoute
  '/admin/settings/': typeof AuthenticatedAdminSettingsIndexRoute
  '/admin/system-health/': typeof AuthenticatedAdminSystemHealthIndexRoute
  '/admin/videos/': typeof AuthenticatedAdminVideosIndexRoute
  '/admin/weekly-question/': typeof AuthenticatedAdminWeeklyQuestionIndexRoute
  '/student/history/': typeof AuthenticatedStudentHistoryIndexRoute
  '/student/live/': typeof AuthenticatedStudentLiveIndexRoute
  '/student/videos/': typeof AuthenticatedStudentVideosIndexRoute
  '/admin/history/$eraId/new-event': typeof AuthenticatedAdminHistoryEraIdNewEventRoute
  '/admin/history/edit/$eraId': typeof AuthenticatedAdminHistoryEditEraIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exams': typeof AuthenticatedExamsRouteWithChildren
  '/kingdom': typeof AuthenticatedKingdomRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/predictions': typeof AuthenticatedPredictionsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/timeline': typeof AuthenticatedTimelineRouteWithChildren
  '/admin/exams': typeof AuthenticatedAdminExamsRouteWithChildren
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/style': typeof AuthenticatedAdminStyleRoute
  '/admin/weekly-winners': typeof AuthenticatedAdminWeeklyWinnersRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/exams/$examId': typeof AuthenticatedExamsExamIdRouteWithChildren
  '/student/weekly-question': typeof AuthenticatedStudentWeeklyQuestionRoute
  '/timeline/$year': typeof AuthenticatedTimelineYearRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/exams/$examId': typeof AuthenticatedAdminExamsExamIdRoute
  '/admin/history/$eraId': typeof AuthenticatedAdminHistoryEraIdRouteWithChildren
  '/admin/history/new-era': typeof AuthenticatedAdminHistoryNewEraRoute
  '/admin/live/$liveId': typeof AuthenticatedAdminLiveLiveIdRoute
  '/admin/live/new': typeof AuthenticatedAdminLiveNewRoute
  '/admin/results/$studentId': typeof AuthenticatedAdminResultsStudentIdRoute
  '/admin/videos/$videoId': typeof AuthenticatedAdminVideosVideoIdRoute
  '/admin/videos/new': typeof AuthenticatedAdminVideosNewRoute
  '/exams/$examId/result': typeof AuthenticatedExamsExamIdResultRoute
  '/student/history/$eraId': typeof AuthenticatedStudentHistoryEraIdRoute
  '/student/live/$liveId': typeof AuthenticatedStudentLiveLiveIdRoute
  '/student/videos/$videoId': typeof AuthenticatedStudentVideosVideoIdRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsIndexRoute
  '/admin/events': typeof AuthenticatedAdminEventsIndexRoute
  '/admin/history': typeof AuthenticatedAdminHistoryIndexRoute
  '/admin/kingdom': typeof AuthenticatedAdminKingdomIndexRoute
  '/admin/leaderboard': typeof AuthenticatedAdminLeaderboardIndexRoute
  '/admin/live': typeof AuthenticatedAdminLiveIndexRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsIndexRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsIndexRoute
  '/admin/system-health': typeof AuthenticatedAdminSystemHealthIndexRoute
  '/admin/videos': typeof AuthenticatedAdminVideosIndexRoute
  '/admin/weekly-question': typeof AuthenticatedAdminWeeklyQuestionIndexRoute
  '/student/history': typeof AuthenticatedStudentHistoryIndexRoute
  '/student/live': typeof AuthenticatedStudentLiveIndexRoute
  '/student/videos': typeof AuthenticatedStudentVideosIndexRoute
  '/admin/history/$eraId/new-event': typeof AuthenticatedAdminHistoryEraIdNewEventRoute
  '/admin/history/edit/$eraId': typeof AuthenticatedAdminHistoryEditEraIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exams': typeof AuthenticatedExamsRouteWithChildren
  '/_authenticated/kingdom': typeof AuthenticatedKingdomRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/predictions': typeof AuthenticatedPredictionsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/timeline': typeof AuthenticatedTimelineRouteWithChildren
  '/_authenticated/admin/exams': typeof AuthenticatedAdminExamsRouteWithChildren
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/_authenticated/admin/style': typeof AuthenticatedAdminStyleRoute
  '/_authenticated/admin/weekly-winners': typeof AuthenticatedAdminWeeklyWinnersRoute
  '/_authenticated/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/_authenticated/exams/$examId': typeof AuthenticatedExamsExamIdRouteWithChildren
  '/_authenticated/student/weekly-question': typeof AuthenticatedStudentWeeklyQuestionRoute
  '/_authenticated/timeline/$year': typeof AuthenticatedTimelineYearRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/exams/$examId': typeof AuthenticatedAdminExamsExamIdRoute
  '/_authenticated/admin/history/$eraId': typeof AuthenticatedAdminHistoryEraIdRouteWithChildren
  '/_authenticated/admin/history/new-era': typeof AuthenticatedAdminHistoryNewEraRoute
  '/_authenticated/admin/live/$liveId': typeof AuthenticatedAdminLiveLiveIdRoute
  '/_authenticated/admin/live/new': typeof AuthenticatedAdminLiveNewRoute
  '/_authenticated/admin/results/$studentId': typeof AuthenticatedAdminResultsStudentIdRoute
  '/_authenticated/admin/videos/$videoId': typeof AuthenticatedAdminVideosVideoIdRoute
  '/_authenticated/admin/videos/new': typeof AuthenticatedAdminVideosNewRoute
  '/_authenticated/exams/$examId/result': typeof AuthenticatedExamsExamIdResultRoute
  '/_authenticated/student/history/$eraId': typeof AuthenticatedStudentHistoryEraIdRoute
  '/_authenticated/student/live/$liveId': typeof AuthenticatedStudentLiveLiveIdRoute
  '/_authenticated/student/videos/$videoId': typeof AuthenticatedStudentVideosVideoIdRoute
  '/_authenticated/admin/announcements/': typeof AuthenticatedAdminAnnouncementsIndexRoute
  '/_authenticated/admin/events/': typeof AuthenticatedAdminEventsIndexRoute
  '/_authenticated/admin/history/': typeof AuthenticatedAdminHistoryIndexRoute
  '/_authenticated/admin/kingdom/': typeof AuthenticatedAdminKingdomIndexRoute
  '/_authenticated/admin/leaderboard/': typeof AuthenticatedAdminLeaderboardIndexRoute
  '/_authenticated/admin/live/': typeof AuthenticatedAdminLiveIndexRoute
  '/_authenticated/admin/notifications/': typeof AuthenticatedAdminNotificationsIndexRoute
  '/_authenticated/admin/settings/': typeof AuthenticatedAdminSettingsIndexRoute
  '/_authenticated/admin/system-health/': typeof AuthenticatedAdminSystemHealthIndexRoute
  '/_authenticated/admin/videos/': typeof AuthenticatedAdminVideosIndexRoute
  '/_authenticated/admin/weekly-question/': typeof AuthenticatedAdminWeeklyQuestionIndexRoute
  '/_authenticated/student/history/': typeof AuthenticatedStudentHistoryIndexRoute
  '/_authenticated/student/live/': typeof AuthenticatedStudentLiveIndexRoute
  '/_authenticated/student/videos/': typeof AuthenticatedStudentVideosIndexRoute
  '/_authenticated/admin/history/$eraId/new-event': typeof AuthenticatedAdminHistoryEraIdNewEventRoute
  '/_authenticated/admin/history/edit/$eraId': typeof AuthenticatedAdminHistoryEditEraIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/assistant'
    | '/dashboard'
    | '/exams'
    | '/kingdom'
    | '/leaderboard'
    | '/notifications'
    | '/predictions'
    | '/profile'
    | '/timeline'
    | '/admin/exams'
    | '/admin/students'
    | '/admin/style'
    | '/admin/weekly-winners'
    | '/events/$eventId'
    | '/exams/$examId'
    | '/student/weekly-question'
    | '/timeline/$year'
    | '/admin/'
    | '/admin/exams/$examId'
    | '/admin/history/$eraId'
    | '/admin/history/new-era'
    | '/admin/live/$liveId'
    | '/admin/live/new'
    | '/admin/results/$studentId'
    | '/admin/videos/$videoId'
    | '/admin/videos/new'
    | '/exams/$examId/result'
    | '/student/history/$eraId'
    | '/student/live/$liveId'
    | '/student/videos/$videoId'
    | '/admin/announcements/'
    | '/admin/events/'
    | '/admin/history/'
    | '/admin/kingdom/'
    | '/admin/leaderboard/'
    | '/admin/live/'
    | '/admin/notifications/'
    | '/admin/settings/'
    | '/admin/system-health/'
    | '/admin/videos/'
    | '/admin/weekly-question/'
    | '/student/history/'
    | '/student/live/'
    | '/student/videos/'
    | '/admin/history/$eraId/new-event'
    | '/admin/history/edit/$eraId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/assistant'
    | '/dashboard'
    | '/exams'
    | '/kingdom'
    | '/leaderboard'
    | '/notifications'
    | '/predictions'
    | '/profile'
    | '/timeline'
    | '/admin/exams'
    | '/admin/students'
    | '/admin/style'
    | '/admin/weekly-winners'
    | '/events/$eventId'
    | '/exams/$examId'
    | '/student/weekly-question'
    | '/timeline/$year'
    | '/admin'
    | '/admin/exams/$examId'
    | '/admin/history/$eraId'
    | '/admin/history/new-era'
    | '/admin/live/$liveId'
    | '/admin/live/new'
    | '/admin/results/$studentId'
    | '/admin/videos/$videoId'
    | '/admin/videos/new'
    | '/exams/$examId/result'
    | '/student/history/$eraId'
    | '/student/live/$liveId'
    | '/student/videos/$videoId'
    | '/admin/announcements'
    | '/admin/events'
    | '/admin/history'
    | '/admin/kingdom'
    | '/admin/leaderboard'
    | '/admin/live'
    | '/admin/notifications'
    | '/admin/settings'
    | '/admin/system-health'
    | '/admin/videos'
    | '/admin/weekly-question'
    | '/student/history'
    | '/student/live'
    | '/student/videos'
    | '/admin/history/$eraId/new-event'
    | '/admin/history/edit/$eraId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/assistant'
    | '/_authenticated/dashboard'
    | '/_authenticated/exams'
    | '/_authenticated/kingdom'
    | '/_authenticated/leaderboard'
    | '/_authenticated/notifications'
    | '/_authenticated/predictions'
    | '/_authenticated/profile'
    | '/_authenticated/timeline'
    | '/_authenticated/admin/exams'
    | '/_authenticated/admin/students'
    | '/_authenticated/admin/style'
    | '/_authenticated/admin/weekly-winners'
    | '/_authenticated/events/$eventId'
    | '/_authenticated/exams/$examId'
    | '/_authenticated/student/weekly-question'
    | '/_authenticated/timeline/$year'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/exams/$examId'
    | '/_authenticated/admin/history/$eraId'
    | '/_authenticated/admin/history/new-era'
    | '/_authenticated/admin/live/$liveId'
    | '/_authenticated/admin/live/new'
    | '/_authenticated/admin/results/$studentId'
    | '/_authenticated/admin/videos/$videoId'
    | '/_authenticated/admin/videos/new'
    | '/_authenticated/exams/$examId/result'
    | '/_authenticated/student/history/$eraId'
    | '/_authenticated/student/live/$liveId'
    | '/_authenticated/student/videos/$videoId'
    | '/_authenticated/admin/announcements/'
    | '/_authenticated/admin/events/'
    | '/_authenticated/admin/history/'
    | '/_authenticated/admin/kingdom/'
    | '/_authenticated/admin/leaderboard/'
    | '/_authenticated/admin/live/'
    | '/_authenticated/admin/notifications/'
    | '/_authenticated/admin/settings/'
    | '/_authenticated/admin/system-health/'
    | '/_authenticated/admin/videos/'
    | '/_authenticated/admin/weekly-question/'
    | '/_authenticated/student/history/'
    | '/_authenticated/student/live/'
    | '/_authenticated/student/videos/'
    | '/_authenticated/admin/history/$eraId/new-event'
    | '/_authenticated/admin/history/edit/$eraId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/timeline': {
      id: '/_authenticated/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AuthenticatedTimelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/predictions': {
      id: '/_authenticated/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof AuthenticatedPredictionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kingdom': {
      id: '/_authenticated/kingdom'
      path: '/kingdom'
      fullPath: '/kingdom'
      preLoaderRoute: typeof AuthenticatedKingdomRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams': {
      id: '/_authenticated/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof AuthenticatedExamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/timeline/$year': {
      id: '/_authenticated/timeline/$year'
      path: '/$year'
      fullPath: '/timeline/$year'
      preLoaderRoute: typeof AuthenticatedTimelineYearRouteImport
      parentRoute: typeof AuthenticatedTimelineRoute
    }
    '/_authenticated/student/weekly-question': {
      id: '/_authenticated/student/weekly-question'
      path: '/student/weekly-question'
      fullPath: '/student/weekly-question'
      preLoaderRoute: typeof AuthenticatedStudentWeeklyQuestionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/$examId': {
      id: '/_authenticated/exams/$examId'
      path: '/$examId'
      fullPath: '/exams/$examId'
      preLoaderRoute: typeof AuthenticatedExamsExamIdRouteImport
      parentRoute: typeof AuthenticatedExamsRoute
    }
    '/_authenticated/events/$eventId': {
      id: '/_authenticated/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AuthenticatedEventsEventIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/weekly-winners': {
      id: '/_authenticated/admin/weekly-winners'
      path: '/weekly-winners'
      fullPath: '/admin/weekly-winners'
      preLoaderRoute: typeof AuthenticatedAdminWeeklyWinnersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/style': {
      id: '/_authenticated/admin/style'
      path: '/style'
      fullPath: '/admin/style'
      preLoaderRoute: typeof AuthenticatedAdminStyleRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/exams': {
      id: '/_authenticated/admin/exams'
      path: '/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AuthenticatedAdminExamsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/student/videos/': {
      id: '/_authenticated/student/videos/'
      path: '/student/videos'
      fullPath: '/student/videos/'
      preLoaderRoute: typeof AuthenticatedStudentVideosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/live/': {
      id: '/_authenticated/student/live/'
      path: '/student/live'
      fullPath: '/student/live/'
      preLoaderRoute: typeof AuthenticatedStudentLiveIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/history/': {
      id: '/_authenticated/student/history/'
      path: '/student/history'
      fullPath: '/student/history/'
      preLoaderRoute: typeof AuthenticatedStudentHistoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/weekly-question/': {
      id: '/_authenticated/admin/weekly-question/'
      path: '/weekly-question'
      fullPath: '/admin/weekly-question/'
      preLoaderRoute: typeof AuthenticatedAdminWeeklyQuestionIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/videos/': {
      id: '/_authenticated/admin/videos/'
      path: '/videos'
      fullPath: '/admin/videos/'
      preLoaderRoute: typeof AuthenticatedAdminVideosIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/system-health/': {
      id: '/_authenticated/admin/system-health/'
      path: '/system-health'
      fullPath: '/admin/system-health/'
      preLoaderRoute: typeof AuthenticatedAdminSystemHealthIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings/': {
      id: '/_authenticated/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AuthenticatedAdminSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifications/': {
      id: '/_authenticated/admin/notifications/'
      path: '/notifications'
      fullPath: '/admin/notifications/'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/live/': {
      id: '/_authenticated/admin/live/'
      path: '/live'
      fullPath: '/admin/live/'
      preLoaderRoute: typeof AuthenticatedAdminLiveIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leaderboard/': {
      id: '/_authenticated/admin/leaderboard/'
      path: '/leaderboard'
      fullPath: '/admin/leaderboard/'
      preLoaderRoute: typeof AuthenticatedAdminLeaderboardIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/kingdom/': {
      id: '/_authenticated/admin/kingdom/'
      path: '/kingdom'
      fullPath: '/admin/kingdom/'
      preLoaderRoute: typeof AuthenticatedAdminKingdomIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/history/': {
      id: '/_authenticated/admin/history/'
      path: '/history'
      fullPath: '/admin/history/'
      preLoaderRoute: typeof AuthenticatedAdminHistoryIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/events/': {
      id: '/_authenticated/admin/events/'
      path: '/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AuthenticatedAdminEventsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/announcements/': {
      id: '/_authenticated/admin/announcements/'
      path: '/announcements'
      fullPath: '/admin/announcements/'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/student/videos/$videoId': {
      id: '/_authenticated/student/videos/$videoId'
      path: '/student/videos/$videoId'
      fullPath: '/student/videos/$videoId'
      preLoaderRoute: typeof AuthenticatedStudentVideosVideoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/live/$liveId': {
      id: '/_authenticated/student/live/$liveId'
      path: '/student/live/$liveId'
      fullPath: '/student/live/$liveId'
      preLoaderRoute: typeof AuthenticatedStudentLiveLiveIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/history/$eraId': {
      id: '/_authenticated/student/history/$eraId'
      path: '/student/history/$eraId'
      fullPath: '/student/history/$eraId'
      preLoaderRoute: typeof AuthenticatedStudentHistoryEraIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/$examId/result': {
      id: '/_authenticated/exams/$examId/result'
      path: '/result'
      fullPath: '/exams/$examId/result'
      preLoaderRoute: typeof AuthenticatedExamsExamIdResultRouteImport
      parentRoute: typeof AuthenticatedExamsExamIdRoute
    }
    '/_authenticated/admin/videos/new': {
      id: '/_authenticated/admin/videos/new'
      path: '/videos/new'
      fullPath: '/admin/videos/new'
      preLoaderRoute: typeof AuthenticatedAdminVideosNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/videos/$videoId': {
      id: '/_authenticated/admin/videos/$videoId'
      path: '/videos/$videoId'
      fullPath: '/admin/videos/$videoId'
      preLoaderRoute: typeof AuthenticatedAdminVideosVideoIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/results/$studentId': {
      id: '/_authenticated/admin/results/$studentId'
      path: '/results/$studentId'
      fullPath: '/admin/results/$studentId'
      preLoaderRoute: typeof AuthenticatedAdminResultsStudentIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/live/new': {
      id: '/_authenticated/admin/live/new'
      path: '/live/new'
      fullPath: '/admin/live/new'
      preLoaderRoute: typeof AuthenticatedAdminLiveNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/live/$liveId': {
      id: '/_authenticated/admin/live/$liveId'
      path: '/live/$liveId'
      fullPath: '/admin/live/$liveId'
      preLoaderRoute: typeof AuthenticatedAdminLiveLiveIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/history/new-era': {
      id: '/_authenticated/admin/history/new-era'
      path: '/history/new-era'
      fullPath: '/admin/history/new-era'
      preLoaderRoute: typeof AuthenticatedAdminHistoryNewEraRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/history/$eraId': {
      id: '/_authenticated/admin/history/$eraId'
      path: '/history/$eraId'
      fullPath: '/admin/history/$eraId'
      preLoaderRoute: typeof AuthenticatedAdminHistoryEraIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/exams/$examId': {
      id: '/_authenticated/admin/exams/$examId'
      path: '/$examId'
      fullPath: '/admin/exams/$examId'
      preLoaderRoute: typeof AuthenticatedAdminExamsExamIdRouteImport
      parentRoute: typeof AuthenticatedAdminExamsRoute
    }
    '/_authenticated/admin/history/edit/$eraId': {
      id: '/_authenticated/admin/history/edit/$eraId'
      path: '/history/edit/$eraId'
      fullPath: '/admin/history/edit/$eraId'
      preLoaderRoute: typeof AuthenticatedAdminHistoryEditEraIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/history/$eraId/new-event': {
      id: '/_authenticated/admin/history/$eraId/new-event'
      path: '/new-event'
      fullPath: '/admin/history/$eraId/new-event'
      preLoaderRoute: typeof AuthenticatedAdminHistoryEraIdNewEventRouteImport
      parentRoute: typeof AuthenticatedAdminHistoryEraIdRoute
    }
  }
}

interface AuthenticatedAdminExamsRouteChildren {
  AuthenticatedAdminExamsExamIdRoute: typeof AuthenticatedAdminExamsExamIdRoute
}

const AuthenticatedAdminExamsRouteChildren: AuthenticatedAdminExamsRouteChildren =
  {
    AuthenticatedAdminExamsExamIdRoute: AuthenticatedAdminExamsExamIdRoute,
  }

const AuthenticatedAdminExamsRouteWithChildren =
  AuthenticatedAdminExamsRoute._addFileChildren(
    AuthenticatedAdminExamsRouteChildren,
  )

interface AuthenticatedAdminHistoryEraIdRouteChildren {
  AuthenticatedAdminHistoryEraIdNewEventRoute: typeof AuthenticatedAdminHistoryEraIdNewEventRoute
}

const AuthenticatedAdminHistoryEraIdRouteChildren: AuthenticatedAdminHistoryEraIdRouteChildren =
  {
    AuthenticatedAdminHistoryEraIdNewEventRoute:
      AuthenticatedAdminHistoryEraIdNewEventRoute,
  }

const AuthenticatedAdminHistoryEraIdRouteWithChildren =
  AuthenticatedAdminHistoryEraIdRoute._addFileChildren(
    AuthenticatedAdminHistoryEraIdRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminExamsRoute: typeof AuthenticatedAdminExamsRouteWithChildren
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRoute
  AuthenticatedAdminStyleRoute: typeof AuthenticatedAdminStyleRoute
  AuthenticatedAdminWeeklyWinnersRoute: typeof AuthenticatedAdminWeeklyWinnersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminHistoryEraIdRoute: typeof AuthenticatedAdminHistoryEraIdRouteWithChildren
  AuthenticatedAdminHistoryNewEraRoute: typeof AuthenticatedAdminHistoryNewEraRoute
  AuthenticatedAdminLiveLiveIdRoute: typeof AuthenticatedAdminLiveLiveIdRoute
  AuthenticatedAdminLiveNewRoute: typeof AuthenticatedAdminLiveNewRoute
  AuthenticatedAdminResultsStudentIdRoute: typeof AuthenticatedAdminResultsStudentIdRoute
  AuthenticatedAdminVideosVideoIdRoute: typeof AuthenticatedAdminVideosVideoIdRoute
  AuthenticatedAdminVideosNewRoute: typeof AuthenticatedAdminVideosNewRoute
  AuthenticatedAdminAnnouncementsIndexRoute: typeof AuthenticatedAdminAnnouncementsIndexRoute
  AuthenticatedAdminEventsIndexRoute: typeof AuthenticatedAdminEventsIndexRoute
  AuthenticatedAdminHistoryIndexRoute: typeof AuthenticatedAdminHistoryIndexRoute
  AuthenticatedAdminKingdomIndexRoute: typeof AuthenticatedAdminKingdomIndexRoute
  AuthenticatedAdminLeaderboardIndexRoute: typeof AuthenticatedAdminLeaderboardIndexRoute
  AuthenticatedAdminLiveIndexRoute: typeof AuthenticatedAdminLiveIndexRoute
  AuthenticatedAdminNotificationsIndexRoute: typeof AuthenticatedAdminNotificationsIndexRoute
  AuthenticatedAdminSettingsIndexRoute: typeof AuthenticatedAdminSettingsIndexRoute
  AuthenticatedAdminSystemHealthIndexRoute: typeof AuthenticatedAdminSystemHealthIndexRoute
  AuthenticatedAdminVideosIndexRoute: typeof AuthenticatedAdminVideosIndexRoute
  AuthenticatedAdminWeeklyQuestionIndexRoute: typeof AuthenticatedAdminWeeklyQuestionIndexRoute
  AuthenticatedAdminHistoryEditEraIdRoute: typeof AuthenticatedAdminHistoryEditEraIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminExamsRoute: AuthenticatedAdminExamsRouteWithChildren,
  AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRoute,
  AuthenticatedAdminStyleRoute: AuthenticatedAdminStyleRoute,
  AuthenticatedAdminWeeklyWinnersRoute: AuthenticatedAdminWeeklyWinnersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminHistoryEraIdRoute:
    AuthenticatedAdminHistoryEraIdRouteWithChildren,
  AuthenticatedAdminHistoryNewEraRoute: AuthenticatedAdminHistoryNewEraRoute,
  AuthenticatedAdminLiveLiveIdRoute: AuthenticatedAdminLiveLiveIdRoute,
  AuthenticatedAdminLiveNewRoute: AuthenticatedAdminLiveNewRoute,
  AuthenticatedAdminResultsStudentIdRoute:
    AuthenticatedAdminResultsStudentIdRoute,
  AuthenticatedAdminVideosVideoIdRoute: AuthenticatedAdminVideosVideoIdRoute,
  AuthenticatedAdminVideosNewRoute: AuthenticatedAdminVideosNewRoute,
  AuthenticatedAdminAnnouncementsIndexRoute:
    AuthenticatedAdminAnnouncementsIndexRoute,
  AuthenticatedAdminEventsIndexRoute: AuthenticatedAdminEventsIndexRoute,
  AuthenticatedAdminHistoryIndexRoute: AuthenticatedAdminHistoryIndexRoute,
  AuthenticatedAdminKingdomIndexRoute: AuthenticatedAdminKingdomIndexRoute,
  AuthenticatedAdminLeaderboardIndexRoute:
    AuthenticatedAdminLeaderboardIndexRoute,
  AuthenticatedAdminLiveIndexRoute: AuthenticatedAdminLiveIndexRoute,
  AuthenticatedAdminNotificationsIndexRoute:
    AuthenticatedAdminNotificationsIndexRoute,
  AuthenticatedAdminSettingsIndexRoute: AuthenticatedAdminSettingsIndexRoute,
  AuthenticatedAdminSystemHealthIndexRoute:
    AuthenticatedAdminSystemHealthIndexRoute,
  AuthenticatedAdminVideosIndexRoute: AuthenticatedAdminVideosIndexRoute,
  AuthenticatedAdminWeeklyQuestionIndexRoute:
    AuthenticatedAdminWeeklyQuestionIndexRoute,
  AuthenticatedAdminHistoryEditEraIdRoute:
    AuthenticatedAdminHistoryEditEraIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedExamsExamIdRouteChildren {
  AuthenticatedExamsExamIdResultRoute: typeof AuthenticatedExamsExamIdResultRoute
}

const AuthenticatedExamsExamIdRouteChildren: AuthenticatedExamsExamIdRouteChildren =
  {
    AuthenticatedExamsExamIdResultRoute: AuthenticatedExamsExamIdResultRoute,
  }

const AuthenticatedExamsExamIdRouteWithChildren =
  AuthenticatedExamsExamIdRoute._addFileChildren(
    AuthenticatedExamsExamIdRouteChildren,
  )

interface AuthenticatedExamsRouteChildren {
  AuthenticatedExamsExamIdRoute: typeof AuthenticatedExamsExamIdRouteWithChildren
}

const AuthenticatedExamsRouteChildren: AuthenticatedExamsRouteChildren = {
  AuthenticatedExamsExamIdRoute: AuthenticatedExamsExamIdRouteWithChildren,
}

const AuthenticatedExamsRouteWithChildren =
  AuthenticatedExamsRoute._addFileChildren(AuthenticatedExamsRouteChildren)

interface AuthenticatedTimelineRouteChildren {
  AuthenticatedTimelineYearRoute: typeof AuthenticatedTimelineYearRoute
}

const AuthenticatedTimelineRouteChildren: AuthenticatedTimelineRouteChildren = {
  AuthenticatedTimelineYearRoute: AuthenticatedTimelineYearRoute,
}

const AuthenticatedTimelineRouteWithChildren =
  AuthenticatedTimelineRoute._addFileChildren(
    AuthenticatedTimelineRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExamsRoute: typeof AuthenticatedExamsRouteWithChildren
  AuthenticatedKingdomRoute: typeof AuthenticatedKingdomRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPredictionsRoute: typeof AuthenticatedPredictionsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedTimelineRoute: typeof AuthenticatedTimelineRouteWithChildren
  AuthenticatedEventsEventIdRoute: typeof AuthenticatedEventsEventIdRoute
  AuthenticatedStudentWeeklyQuestionRoute: typeof AuthenticatedStudentWeeklyQuestionRoute
  AuthenticatedStudentHistoryEraIdRoute: typeof AuthenticatedStudentHistoryEraIdRoute
  AuthenticatedStudentLiveLiveIdRoute: typeof AuthenticatedStudentLiveLiveIdRoute
  AuthenticatedStudentVideosVideoIdRoute: typeof AuthenticatedStudentVideosVideoIdRoute
  AuthenticatedStudentHistoryIndexRoute: typeof AuthenticatedStudentHistoryIndexRoute
  AuthenticatedStudentLiveIndexRoute: typeof AuthenticatedStudentLiveIndexRoute
  AuthenticatedStudentVideosIndexRoute: typeof AuthenticatedStudentVideosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExamsRoute: AuthenticatedExamsRouteWithChildren,
  AuthenticatedKingdomRoute: AuthenticatedKingdomRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPredictionsRoute: AuthenticatedPredictionsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedTimelineRoute: AuthenticatedTimelineRouteWithChildren,
  AuthenticatedEventsEventIdRoute: AuthenticatedEventsEventIdRoute,
  AuthenticatedStudentWeeklyQuestionRoute:
    AuthenticatedStudentWeeklyQuestionRoute,
  AuthenticatedStudentHistoryEraIdRoute: AuthenticatedStudentHistoryEraIdRoute,
  AuthenticatedStudentLiveLiveIdRoute: AuthenticatedStudentLiveLiveIdRoute,
  AuthenticatedStudentVideosVideoIdRoute:
    AuthenticatedStudentVideosVideoIdRoute,
  AuthenticatedStudentHistoryIndexRoute: AuthenticatedStudentHistoryIndexRoute,
  AuthenticatedStudentLiveIndexRoute: AuthenticatedStudentLiveIndexRoute,
  AuthenticatedStudentVideosIndexRoute: AuthenticatedStudentVideosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
